//Generate an Enum for all cities in iran

export enum ProvincesEnum {
  East_Azarbaijan = 'East_Azarbaijan',
  West_Azarbaijan = 'West_Azarbaijan',
  Ardabil = 'Ardabil',
  Isfahan = 'Isfahan',
  Alborz = 'Alborz',
  Ilam = 'Ilam',
  Bushehr = 'Bushehr',
  Tehran = 'Tehran',
  Chaharmahal_Bakhtiari = 'Chaharmahal_Bakhtiari',
  South_Khorasan = 'South_Khorasan',
  Razavi_Khorasan = 'Razavi_Khorasan',
  North_Khorasan = 'North_Khorasan',
  Khuzestan = 'Khuzestan',
  Zanjan = 'Zanjan',
  Semnan = 'Semnan',
  Sistan_Baluchestan = 'Sistan_Baluchestan',
  Fars = 'Fars',
  Qazvin = 'Qazvin',
  Qom = 'Qom',
  Kurdistan = 'Kurdistan',
  Kerman = 'Kerman',
  Kermanshah = 'Kermanshah',
  Kohgiluyeh_Boyer_Ahmad = 'Kohgiluyeh_Boyer_Ahmad',
  Golestan = 'Golestan',
  Lorestan = 'Lorestan',
  Gilan = 'Gilan',
  Mazandaran = 'Mazandaran',
  Markazi = 'Markazi',
  Hormozgan = 'Hormozgan',
  Hamedan = 'Hamedan',
  Yazd = 'Yazd',
}
